# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 03:42
from __future__ import unicode_literals

import base.validators
from django.db import migrations, models
import django.db.models.deletion
import owners.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('inn', models.CharField(max_length=15, validators=(owners.validators.validate_inn,))),
                ('kpp', models.CharField(max_length=15, validators=(owners.validators.validate_kpp,))),
                ('legal_address', models.CharField(max_length=512)),
                ('actual_address', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=(base.validators.validate_phone_number,))),
                ('use_user_data', models.BooleanField(default=False)),
                ('checking_account', models.CharField(max_length=64)),
                ('checking_kpp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=(owners.validators.validate_name,))),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=13, validators=(base.validators.validate_phone_number,))),
                ('comment', models.CharField(blank=True, max_length=1023, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=63, null=True)),
                ('last_name', models.CharField(blank=True, max_length=63, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('sms_code', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(default=b'stub', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email_confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EmailConfirmation')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='OwnerSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=63)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner')),
            ],
            options={
                'ordering': ['-expired_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpgradeIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.IntegerField(choices=[(0, 'Software update'), (1, 'Install readers')])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Viewed'), (2, 'Processing'), (3, 'Processed'), (-1, 'Cancelled')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='connectissue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Owner'),
        ),
    ]
