# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='stublogin', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
