# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_auto_20181205_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='use_user_data',
            new_name='use_profile_contacts',
        ),
        migrations.AddField(
            model_name='company',
            name='bic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
