# Generated by Django 2.1.5 on 2020-01-10 21:23

from django.db import migrations, models
import django.db.models.deletion
import owners.models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_auto_20200110_2052'),
        ('owners', '0002_auto_20200110_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Company')),
            ],
            options={
                'db_table': 'owner_report',
            },
        ),
        migrations.CreateModel(
            name='CompanySettingReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('report_emails', models.TextField(blank=True, null=True, validators=[owners.models.comma_separated_emails])),
                ('period_in_days', models.IntegerField(default=30)),
                ('last_send_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Company')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
            ],
            options={
                'db_table': 'report_settings',
            },
        ),
    ]
