# Generated by Django 2.1.5 on 2020-01-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200111_1219'),
        ('owners', '0003_companyreport_companysettingreports_ownerpaymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreport',
            name='invoice_withdraw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.InvoiceWithdraw'),
        ),
    ]
