# Generated by Django 2.1 on 2021-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_auto_20200111_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
    ]
