# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-12 10:11
from __future__ import unicode_literals

import base.validators
from django.db import migrations, models
import owners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_auto_20181113_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='use_profile_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(max_length=15, validators=(owners.validators.validate_inn,)),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(max_length=15, validators=(owners.validators.validate_kpp,)),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15, validators=(base.validators.validate_phone_number,)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=255, validators=(owners.validators.validate_name,)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='phone',
            field=models.CharField(max_length=13, validators=(base.validators.validate_phone_number,)),
        ),
    ]
