# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-25 16:28
from __future__ import unicode_literals

import base.validators
from django.db import migrations, models
import owners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_auto_20181212_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='checking_account',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='checking_kpp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(owners.validators.validate_kpp,)),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(base.validators.validate_phone_number,)),
        ),
    ]
