# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import owners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_auto_20181225_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(owners.validators.validate_inn,)),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(owners.validators.validate_kpp,)),
        ),
    ]
