# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-10 15:13
from __future__ import unicode_literals

import accounts.validators
import base.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_auto_20190110_1513'),
        ('parkings', '0023_auto_20181212_1011'),
        ('owners', '0008_auto_20181227_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Connect parking'), (2, 'Software update'), (3, 'Install readers')])),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Processing'), (3, 'Processed'), (4, 'Cancelled')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Owner')),
                ('parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Type owner'), (2, b'Type vendor')])),
                ('name', models.CharField(max_length=255, validators=(accounts.validators.validate_name,))),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=13, validators=(base.validators.validate_phone_number,))),
                ('comment', models.CharField(blank=True, max_length=1023, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='connectissue',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='connectissue',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='connectissue',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.RemoveField(
            model_name='upgradeissue',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ConnectIssue',
        ),
        migrations.DeleteModel(
            name='UpgradeIssue',
        ),
    ]
