# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-12 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0009_auto_20190110_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='checking_account',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='company',
            name='checking_kpp',
        ),
    ]
