# Generated by Django 2.2 on 2022-04-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0020_auto_20220411_0734'),
        ('owners', '0009_auto_20211108_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUsersPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUsersPermissionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Company users permission categories',
            },
        ),
        migrations.CreateModel(
            name='CompanyUsersRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(db_index=True, default='standard', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Company owner', 'verbose_name_plural': 'Company owners'},
        ),
        migrations.CreateModel(
            name='CompanyUsersRolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.CompanyUsersPermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.CompanyUsersRole')),
            ],
        ),
        migrations.AddField(
            model_name='companyusersrole',
            name='permissions',
            field=models.ManyToManyField(related_name='_companyusersrole_permissions_+', through='owners.CompanyUsersRolePermission', to='owners.CompanyUsersPermission'),
        ),
        migrations.AddField(
            model_name='companyuserspermission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.CompanyUsersPermissionCategory'),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('middle_name', models.CharField(blank=True, max_length=63, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('available_parking', models.ManyToManyField(to='parkings.Parking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.Company')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.CompanyUser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.CompanyUsersRole')),
            ],
        ),
    ]
