# Generated by Django 2.2 on 2022-04-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0010_auto_20220415_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuserspermission',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
