# Generated by Django 2.2 on 2022-04-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0011_companyuserspermission_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyusersrole',
            name='permissions',
            field=models.ManyToManyField(through='owners.CompanyUsersRolePermission', to='owners.CompanyUsersPermission'),
        ),
    ]
