# Generated by Django 2.2 on 2022-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0012_auto_20220415_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuserspermission',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='companyuserspermission',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
