# Generated by Django 2.2 on 2022-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0013_auto_20220415_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyusersrole',
            name='type',
            field=models.CharField(choices=[('standard', 'standard'), ('individual', 'individual')], db_index=True, default='standard', max_length=100),
        ),
    ]
