# Generated by Django 2.2 on 2022-04-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0014_auto_20220418_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
