# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0015_companysettingreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettingreports',
            name='last_send_date',
            field=models.DateTimeField(),
        ),
    ]
