# Generated by Django 2.2 on 2022-04-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0016_auto_20220418_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.CompanyUser'),
        ),
    ]
