# Generated by Django 2.2 on 2022-04-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0017_auto_20220421_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.CompanyUsersRole'),
        ),
    ]
