# Generated by Django 2.2 on 2022-04-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0018_auto_20220427_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
