# Generated by Django 2.2 on 2022-04-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0019_auto_20220427_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusersrole',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Company'),
        ),
    ]
