# Generated by Django 2.2 on 2022-04-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0020_companyusersrole_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyusersrole',
            name='type',
        ),
    ]
