# Generated by Django 2.2 on 2022-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0022_auto_20220430_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='valet_users_avatars'),
        ),
    ]
