# Generated by Django 2.2 on 2022-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0023_auto_20220516_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
