# Generated by Django 2.1.5 on 2020-01-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentNumber', models.TextField(blank=True, help_text='Номер документа', null=True)),
                ('documentDate', models.DateField(blank=True, help_text='Дата документа', null=True)),
                ('amount', models.IntegerField(help_text='Сумма платежа')),
                ('recipientName', models.TextField(help_text='Получатель')),
                ('inn', models.TextField()),
                ('kpp', models.TextField()),
                ('accountNumber', models.TextField(help_text='Номер счета получателя')),
                ('bankAcnt', models.TextField(blank=True, help_text='Банк получателя', null=True)),
                ('bankBik', models.TextField(blank=True, help_text='БИК банка получателя', null=True)),
                ('paymentPurpose', models.TextField(blank=True, default='', help_text='Назначение платежа')),
                ('executionOrder', models.IntegerField(default=0, help_text='Очередность платежа')),
                ('taxPayerStatus', models.TextField(blank=True, help_text='Статус составителя расчетного документа', null=True)),
                ('kbk', models.TextField(blank=True, help_text='Код бюджетной классификации', null=True)),
                ('oktmo', models.TextField(blank=True, help_text='Код ОКТМО территории, на которой мобилизуютсяденежные средства от уплаты налога, сбора и иного платежа', null=True)),
                ('taxEvidence', models.TextField(blank=True, help_text='Основание налогового платежа', null=True)),
                ('taxPeriod', models.TextField(blank=True, help_text='Налоговый период / код таможенного органа', null=True)),
                ('uin', models.TextField(blank=True, help_text='Уникальный идентификатор платежа', null=True)),
                ('taxDocNumber', models.TextField(blank=True, help_text='Номер налогового документа', null=True)),
                ('taxDocDate', models.TextField(blank=True, help_text='Дата налогового документа', null=True)),
                ('is_send', models.BooleanField(default=False)),
                ('error', models.TextField()),
            ],
            options={
                'db_table': 'invoice_withdraw',
            },
        )
    ]
