# Generated by Django 2.1.5 on 2020-01-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0002_rpssubscription'),
        ('payments', '0002_invoicewithdraw_tinkoffsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsSubscription'),
        ),
    ]
