# Generated by Django 2.1.5 on 2020-01-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinkoffSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField(blank=True, null=True)),
                ('expires_in', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tinkoff_session',
            },
        ),
        migrations.AddField(
            model_name='invoicewithdraw',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicewithdraw',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
