# Generated by Django 2.1 on 2020-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200111_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinkoffpayment',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Unknown'), (0, 'Init'), (1, 'New'), (2, 'Cancel'), (3, 'Form showed'), (4, 'Rejected'), (5, 'Auth fail'), (6, 'Authorized'), (7, 'Confirmed'), (9, 'Refunded'), (10, 'Partial_refunded'), (12, 'Authorization prepared')], default=0),
        ),
    ]
