# Generated by Django 2.1 on 2020-05-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200303_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicewithdraw',
            name='responseDocumentId',
            field=models.TextField(blank=True, help_text='Идентифиакор созданного платежного поручения', null=True),
        ),
    ]
