# Generated by Django 2.1 on 2020-06-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('payments', '0006_invoicewithdraw_responsedocumentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Terminal'),
        ),
    ]
