# Generated by Django 2.1 on 2021-02-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_order_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBankPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('reason_code', models.SmallIntegerField(default=-1)),
                ('receipt_data', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Order')),
            ],
            options={
                'verbose_name': 'HomeBank Payment',
                'verbose_name_plural': 'HomeBank Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='creditcard',
            name='bank',
            field=models.CharField(choices=[('Тинькофф', 'tinkoff'), ('HomeBank', 'homebank')], default='tinkoff', max_length=61),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_char_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_id',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='exp_date',
            field=models.CharField(blank=True, max_length=61, null=True),
        ),
    ]
