# Generated by Django 2.2.16 on 2024-07-16 03:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_order_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
