# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20180513_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fiscal_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.FiskalNotification'),
        ),
    ]
