# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-20 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_order_fiscal_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='rebill_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
