# Generated by Django 2.1 on 2021-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210201_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebankpayment',
            name='status',
            field=models.CharField(blank=True, default='init', max_length=60),
        ),
    ]
