# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-07 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20180520_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
