# Generated by Django 2.1 on 2021-02-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20210202_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='bank',
            new_name='acquiring',
        ),
        migrations.AddField(
            model_name='order',
            name='acquiring',
            field=models.CharField(choices=[('tinkoff', 'Tinkoff'), ('homebank', 'Homebank')], default='tinkoff', max_length=20),
        ),
    ]
