# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-10 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20180607_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refunded',
            new_name='refund_request',
        ),
    ]
