# Generated by Django 2.1 on 2021-02-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20210203_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='acquiring',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('homebank', 'HomeBank')], default='tinkoff', max_length=61),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
