# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20180610_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiskalnotification',
            name='fiscal_document_attribute',
            field=models.BigIntegerField(),
        ),
    ]
