# Generated by Django 2.1 on 2021-03-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20210225_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBankFiskalNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.IntegerField()),
                ('shift_number', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('date_time_string', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('ofd_name', models.CharField(max_length=100)),
                ('identity_number', models.IntegerField()),
                ('registration_number', models.CharField(max_length=100)),
                ('unique_number', models.CharField(max_length=100)),
                ('ticket_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='homebank_fiscal_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.HomeBankFiskalNotification'),
        ),
    ]
