# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20180618_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiskalnotification',
            name='token',
        ),
        migrations.AddField(
            model_name='fiskalnotification',
            name='card_pan',
            field=models.CharField(default='', max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paid_card_pan',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
