# Generated by Django 2.1 on 2021-04-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20210316_1631'),
        ('payments', '0008_auto_20210311_1415'),
    ]

    operations = [
    ]
