# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_password'),
        ('payments', '0013_auto_20180620_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardBindRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, b'Created'), (1, b'Inited'), (2, b'Authorized payment'), (3, b'Confirmed payment'), (4, b'Refunding payment request'), (5, b'Refunded payment'), (6, b'Rejected'), (7, b'Error ocurred')], default=0)),
                ('status_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_card_pan',
            field=models.CharField(default=b'', max_length=31),
        ),
        migrations.AlterField(
            model_name='tinkoffpayment',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, b'Unknown'), (0, b'Init'), (1, b'New'), (2, b'Cancel'), (3, b'Form showed'), (4, b'Rejected'), (5, b'Auth fail'), (6, b'Authorized'), (7, b'Confirmed'), (9, b'Refunded'), (10, b'Partial_refunded')], default=0),
        ),
        migrations.AddField(
            model_name='creditcardbindrequest',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.TinkoffPayment'),
        ),
    ]
