# Generated by Django 2.1 on 2021-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20210316_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_refund',
            field=models.BooleanField(default=False),
        ),
    ]
