# Generated by Django 2.1 on 2021-03-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_order_need_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebankpayment',
            name='status',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
