# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20180715_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardbindrequest',
            name='account',
        ),
        migrations.RemoveField(
            model_name='creditcardbindrequest',
            name='payment',
        ),
        migrations.DeleteModel(
            name='CreditCardBindRequest',
        ),
    ]
