# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-22 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20180715_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
