# Generated by Django 2.1 on 2021-04-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210311_1415'),
        ('payments', '0015_auto_20210329_1828'),
    ]

    operations = [
    ]
