# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_order_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_uuid',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
