# Generated by Django 2.1 on 2021-04-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_merge_20210413_1027'),
        ('payments', '0016_merge_20210409_1659'),
    ]

    operations = [
    ]
