# Generated by Django 2.1 on 2021-04-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_merge_20210427_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='need_refund',
            new_name='canceled',
        ),
    ]
