# Generated by Django 2.2 on 2024-07-29 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20210427_1507'),
        ('payments', '0008_order_payload'),
    ]

    operations = [
    ]
