# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-12 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_order_parking_card_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
