# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0030_rpssubscription'),
        ('payments', '0019_order_paid_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsSubscription'),
        ),
    ]
