# Generated by Django 2.2 on 2025-07-28 02:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_merge_20240729_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzumBankPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_id', models.CharField(max_length=64, unique=True)),
                ('uzum_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Зарегистрирован'), ('COMPLETED', 'Завершён'), ('DECLINED', 'Отклонён'), ('REFUNDED', 'Возврат'), ('AUTHORIZED', 'Холд средств'), ('REVERSED', 'Отменён'), ('ERROR', 'Ошибка')], default='REGISTERED', max_length=32)),
                ('amount', models.PositiveIntegerField(help_text='Сумма в тийинах')),
                ('raw_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzum_payments', to='payments.Order')),
            ],
            options={
                'verbose_name': 'Платёж через UzumBank',
                'verbose_name_plural': 'Платежи через UzumBank',
                'db_table': 'uzum_bank_payment',
            },
        ),
    ]
