# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_terminal_name'),
        ('payments', '0020_order_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Terminal'),
        ),
    ]
