# Generated by Django 2.2 on 2025-07-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_uzumbankpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzumbankpayment',
            name='payment_url',
            field=models.URLField(blank=True, help_text='URL для редиректа пользователя на страницу оплаты UzumBank', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='acquiring',
            field=models.CharField(choices=[('tinkoff', 'Тинькофф'), ('homebank', 'HomeBank'), ('uzumbank', 'UzumBank')], default='tinkoff', max_length=61),
        ),
        migrations.AlterField(
            model_name='order',
            name='acquiring',
            field=models.CharField(choices=[('tinkoff', 'Tinkoff'), ('homebank', 'Homebank'), ('uzumbank', 'UzumBank')], default='tinkoff', max_length=20),
        ),
    ]
