# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_order_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refunded_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
