version: '3'
networks:
    main_net:
        driver: bridge
services:
    parkpass-postgres:
        container_name: parkpass-postgres
        image: postgres:9.6
        restart: always
        networks:
            - main_net
        environment:
            - POSTGRES_USER=parkpass
            - POSTGRES_PASSWORD=parkpass
            - POSTGRES_DBNAME=parkpass
            - ALLOW_IP_RANGE=0.0.0.0/0

        volumes:
            - ./data/postgresql-data:/var/lib/postgresql/data
        expose:
            - "5432"
        ports:
            - "5432:5432"

    parkpass-web:
        depends_on:
            - parkpass-postgres
        container_name: parkpass-web
        image: bugor/parkpass:latest
        networks:
            - main_net
        restart: always
        environment:
            - PROD=1
            - PORT=8000
            - POSTGRES_DATABASE_HOST=parkpass-postgres
            - POSTGRES_DB_NAME=parkpass
            - POSTGRES_USER=parkpass
            - POSTGRES_PASSWORD=parkpass
        ports:
            - "5000:80"