[uwsgi]
socket = 0.0.0.0:8000

# Обеспечение стабильной работы
master = true
processes = 8  # Количество процессов uWSGI. Подберите оптимальное значение в зависимости от ресурсов сервера.
threads = 4    # Отключение потоков, устанавливаем в 1 для совместимости

harakiri = 180             ; Перезапуск рабочих процессов, если они зависли на одном запросе
max-requests = 1000        ; Перезапуск рабочих процессов после обработки этого количества запросов
max-worker-lifetime = 3600 ; Перезапуск рабочих процессов после этого количества секунд

# WSGI модуль Django
module=parkpass_backend.wsgi:application

# Очистка окружения при выходе
vacuum = true
