# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('canonical_name', models.CharField(max_length=255, unique=True)),
                ('secret', models.TextField()),
            ],
        ),
    ]
