# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[(1, 'MOBILE'), (2, 'WEB')], max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('temp_user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'jwt_session',
            },
        ),
    ]
