# Generated by Django 2.1.5 on 2020-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=1024)),
                ('type', models.IntegerField(choices=[(1, 'MOBILE'), (2, 'WEB')], default=1)),
                ('expires_at', models.DateTimeField()),
                ('temp_user_id', models.BigIntegerField()),
                ('last_expired_access_token', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'db_table': 'jwt_session',
            },
        ),
    ]
