# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='temp_user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.IntegerField(choices=[(1, 'MOBILE'), (2, 'WEB')], default=1),
        ),
    ]
