# Generated by Django 2.2 on 2025-07-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200614_1642'),
        ('parkings', '0004_parking_rps_subscriptions_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recipient_name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('bank_bik', models.CharField(max_length=9)),
                ('bank_account', models.CharField(max_length=20)),
                ('payout_periodicity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('n_days', 'N_days')], default='monthly', max_length=20)),
                ('payout_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('report_emails', models.TextField(help_text='Список email, через запятую')),
                ('auto_send', models.BooleanField(default=False, help_text='Отправлять без подтверждения администратора')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to='accounts.Account')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
            ],
        ),
    ]
