# Generated by Django 2.2 on 2025-07-12 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0004_parking_rps_subscriptions_available'),
        ('accounts', '0002_auto_20200614_1642'),
        ('payments', '0007_order_terminal'),
        ('payments_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPaymentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_refunds', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_sent', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reports', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('invoice_withdraw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.InvoiceWithdraw')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments_reports.ParkingPaymentReport')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingPaymentReportTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('confirmed', 'Confirmed'), ('refund', 'Refund')], max_length=20)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_after_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments_reports.ParkingPaymentReport')),
                ('tinkoff_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.TinkoffPayment')),
            ],
        ),
    ]
