# Generated by Django 2.2 on 2025-07-13 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments_reports', '0002_parkingpaymentreport_parkingpaymentreporttransaction_payouthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreportconfig',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to='owners.Owner'),
        ),
    ]
