# Generated by Django 2.2 on 2025-07-20 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0025_companyuser_telegram_id'),
        ('payments_reports', '0002_parkingpaymentreport_parkingpaymentreporttransaction_payouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreportconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Company'),
        ),
        migrations.AlterField(
            model_name='parkingpaymentreport',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reports', to='owners.Owner'),
        ),
        migrations.AlterField(
            model_name='parkingreportconfig',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to='owners.Owner'),
        ),
    ]
