# Generated by Django 2.2 on 2025-07-13 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments_reports', '0003_auto_20250713_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingpaymentreport',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reports', to='owners.Owner'),
        ),
    ]
