# Generated by Django 2.2 on 2025-07-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_reports', '0003_auto_20250720_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingpaymentreport',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parkingpaymentreport',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parkingpaymentreport',
            name='total_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parkingpaymentreport',
            name='total_refunds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
