# Generated by Django 2.2 on 2025-07-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_reports', '0004_auto_20250725_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreportconfig',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parkingreportconfig',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='parkingreportconfig',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
