# Generated by Django 2.2 on 2025-07-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0045_parking_domain'),
        ('payments_reports', '0005_auto_20250725_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingpaymentreport',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reports', to='parkings.Parking'),
        ),
    ]
