# Generated by Django 2.2 on 2025-07-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0025_companyuser_telegram_id'),
        ('payments_reports', '0006_parkingpaymentreport_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingpaymentreport',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='parkingpaymentreport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.Company'),
        ),
    ]
