# Generated by Django 2.2 on 2025-07-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_reports', '0007_auto_20250727_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreportconfig',
            name='payout_periodicity',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('n_days', 'N_days')], default='monthly', max_length=20),
        ),
    ]
