# Generated by Django 2.2 on 2025-07-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments_reports', '0008_auto_20250727_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreportconfig',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to='owners.Owner'),
        ),
    ]
