# Generated by Django 2.1 on 2020-06-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='external_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='external_vendor_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
