# Generated by Django 2.2.16 on 2024-06-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200614_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='car_plate',
            field=models.CharField(default='', max_length=32),
        ),
    ]
