# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='external_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='external_vendor_id',
            field=models.IntegerField(null=True),
        ),
    ]
