# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180513_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='emailconfirmation',
            old_name='emails',
            new_name='email',
        ),
    ]