# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180513_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=b'stub', max_length=255),
        ),
    ]
