# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_confirmation',
        ),
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
