# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '__latest__'),
        ('accounts', '0010_account_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsession',
            options={},
        ),
        migrations.AlterField(
            model_name='account',
            name='email_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EmailConfirmation'),
        ),
    ]