# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 12:50
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[(accounts.models.AccountTypes(b'User'), b'User'), (accounts.models.AccountTypes(b'Vendor'), b'Vendor')], default=accounts.models.AccountTypes(b'User'), max_length=16, verbose_name=b'Type of account'),
        ),
        migrations.AddField(
            model_name='account',
            name='ven_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name=b'Vendor name'),
        ),
        migrations.AddField(
            model_name='account',
            name='ven_secret',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name=b'Vendor secret key'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'E-mail'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email_confirmation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.EmailConfirmation'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name=b'First name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name=b'Last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=15, verbose_name=b'Phone number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sms_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
    ]
