# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180713_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
