# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emailconfirmation'),
        ('accounts', '0011_auto_20180718_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EmailConfirmation'),
        ),
    ]
