# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180824_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsession',
            options={'ordering': ['-expired_at']},
        ),
    ]
