# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190615_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='external_vendor_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
