# Generated by Django 2.1.5 on 2020-01-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCard',
            fields=[
                ('card_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RpsParking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_update_url', models.URLField(blank=True, null=True)),
                ('request_parking_card_debt_url', models.URLField(default='https://parkpass.ru/api/v1/parking/rps/mock/debt/')),
                ('request_payment_authorize_url', models.URLField(default='https://parkpass.ru/api/v1/parking/rps/mock/authorized/')),
                ('request_get_subscriptions_list_url', models.URLField(default='https://parkpass.ru/api/v1/parking/rps/mock/subscriptions/')),
                ('request_subscription_pay_url', models.URLField(default='https://parkpass.ru/api/v1/parking/rps/mock/subscription/pay/')),
                ('polling_enabled', models.BooleanField(default=False)),
                ('last_request_body', models.TextField(blank=True, null=True)),
                ('last_request_date', models.DateTimeField(auto_now_add=True)),
                ('last_response_code', models.IntegerField(default=0)),
                ('last_response_body', models.TextField(blank=True, null=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
            ],
            options={
                'verbose_name': 'RpsParking',
                'verbose_name_plural': 'RpsParking',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RpsParkingCardSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_id', models.IntegerField()),
                ('debt', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Only created'), (2, 'Inited pay'), (3, 'Authorized pay'), (4, 'Confirmed pay'), (5, 'Error')], default=1)),
                ('client_uuid', models.UUIDField(default=None, null=True)),
                ('from_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('parking_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.ParkingCard')),
            ],
        ),
    ]
