# Generated by Django 2.1.5 on 2020-01-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_auto_20200110_2052'),
        ('accounts', '0001_initial'),
        ('rps_vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpsSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('sum', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('prolongation', models.BooleanField(default=True)),
                ('data', models.TextField(blank=True, help_text='Byte array as base64', null=True)),
                ('idts', models.TextField()),
                ('id_transition', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Only created'), (2, 'Inited pay'), (3, 'Authorized pay'), (4, 'Confirmed pay'), (5, 'Error')], default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
            ],
        ),
    ]
