# Generated by Django 2.1 on 2020-05-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0002_rpssubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpssubscription',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
