# Generated by Django 2.1 on 2020-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0003_rpssubscription_unlimited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpssubscription',
            name='unlimited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
