# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0004_auto_20180509_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 11, 30, 19, 837836)),
        ),
    ]
