# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0005_auto_20180509_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpsparking',
            name='last_request',
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='last_request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 12, 43, 37, 429078)),
        ),
    ]
