# Generated by Django 2.1 on 2020-06-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0005_auto_20200614_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsparkingcardsession',
            name='from_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
