# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0006_auto_20180509_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsparking',
            name='polling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 13, 19, 27, 968300)),
        ),
    ]
