# Generated by Django 2.1 on 2020-08-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0006_rpsparkingcardsession_from_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingcard',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
