# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-12 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0007_auto_20180509_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 12, 12, 37, 44, 941047)),
        ),
    ]
