# Generated by Django 2.1 on 2020-08-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0007_auto_20200822_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsparkingcardsession',
            name='leave_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
