# Generated by Django 2.1 on 2021-04-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0009_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopersLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_card_id', models.BigIntegerField()),
                ('type', models.IntegerField(choices=[(0, 'Получение задолженности'), (1, 'Оплата задолженности')])),
                ('debt', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Получение задолженности'), (1, 'Оплата задолженности')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='8598805afb34a8b8a105c3ceb43eca70375a3e89e3ea12cf', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='67dc8542-9c4c-11eb-a360-acde48001122', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='developerslog',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.Developer'),
        ),
        migrations.AddField(
            model_name='developerslog',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsParking'),
        ),
    ]
