# Generated by Django 2.1 on 2021-04-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0010_auto_20210413_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='cea4e15b0b85e522f0de62fd665c62590933d465c714a136', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='feb17abe-a768-11eb-819c-acde48001122', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='developerslog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Success')], default=0),
        ),
    ]
