# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0011_auto_20180513_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 21, 22, 38, 900127)),
        ),
    ]
