# Generated by Django 2.1 on 2021-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0011_auto_20210427_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='f7ccca6807b2c61b89f5f17624a7ac9a1fd083d9d71418f9', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='9e24391a-a769-11eb-a091-acde48001122', max_length=128, unique=True),
        ),
    ]
