# Generated by Django 2.1 on 2021-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0012_auto_20210427_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='71b9169c3cc4fb38f2cf6f70423653c2bd2b4587090f38b6', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='13a419e4-a76a-11eb-a21a-acde48001122', max_length=128, unique=True),
        ),
    ]
