# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-20 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0013_auto_20180517_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 20, 18, 6, 12, 142348)),
        ),
    ]
