# Generated by Django 2.1 on 2021-04-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0013_auto_20210427_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='a63651b94c8593e7a5c6c50259188138c30a98b5c8e3d5dd', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='38b80b78-a76a-11eb-8180-acde48001122', max_length=128, unique=True),
        ),
    ]
