# Generated by Django 2.1 on 2021-08-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0014_auto_20210427_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='be926f3013b4bf4b5faa497f706cf7fe79e633e2564976f4', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='12e7d21a-074c-11ec-8d7c-acde48001122', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='rpssubscription',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
