# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-07 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0015_auto_20180528_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 22, 37, 45, 964407)),
        ),
    ]
