# Generated by Django 2.1 on 2021-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0016_auto_20210828_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='ffaa0b3ae3c164ea5776a16619e96c5c14875b17ac4758f1', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='8be4db3e-07f3-11ec-93d7-acde48001122', max_length=128, unique=True),
        ),
    ]
