# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-09 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0016_auto_20180607_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 13, 33, 44, 732863)),
        ),
    ]
