# Generated by Django 2.1 on 2021-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0017_auto_20210828_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='86d4ba428ed2468211faca71b0b2f7df6e706a8bb008c157', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='d1bf9040-0bcc-11ec-8400-acde48001122', max_length=128, unique=True),
        ),
    ]
