# Generated by Django 2.1 on 2021-09-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0018_auto_20210902_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='25f8c82fde5dda8f26cf32529fab7b14dce400af613e115d', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='88b607f2-0bcd-11ec-a449-acde48001122', max_length=128, unique=True),
        ),
    ]
