# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0019_auto_20180618_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 21, 11, 34, 603235)),
        ),
    ]
