# Generated by Django 2.1 on 2021-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0019_auto_20210902_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpssubscription',
            name='push_notified_about_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rpssubscription',
            name='push_notified_about_soon_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='c84220f5a960b123e10220df122d57c083f2535e8336b738', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='4ab5e824-366f-11ec-8d00-acde48001122', max_length=128, unique=True),
        ),
    ]
