# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0020_auto_20180620_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 12, 27, 37, 52000)),
        ),
    ]
