# Generated by Django 2.1 on 2021-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0020_auto_20211026_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='c6341b181c46bd10a150ed69d41dc4cd269a6c208e475ed8', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='7d221090-3722-11ec-a80e-acde48001122', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='rpssubscription',
            name='push_notified_about_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rpssubscription',
            name='push_notified_about_soon_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
