# Generated by Django 2.1 on 2021-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0022_auto_20211028_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='7af3fa0828d21cafc839bece3a267d57c8ee55910b272a3f', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='c388eda0-37fa-11ec-b1d0-acde48001122', max_length=128, unique=True),
        ),
    ]
