# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0023_auto_20180722_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 19, 10, 34, 838451)),
        ),
    ]
