# Generated by Django 2.1 on 2021-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0023_auto_20211028_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='c92a504135ebdcd4c2815e85fc44a3ecb9edf075ecf0c9e2', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='e7b6d9cc-37fe-11ec-8438-acde48001122', max_length=128, unique=True),
        ),
    ]
