# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 21:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0023_auto_20180718_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 21, 59, 44, 484908)),
        ),
    ]
