# Generated by Django 2.1 on 2021-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0024_auto_20211028_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='d60be904deb1b2a3cb81e65bfdcbf58d717de948c5da7769', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='31a7205a-4088-11ec-9a9e-acde48001122', max_length=128, unique=True),
        ),
    ]
