# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0025_auto_20180824_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
