# Generated by Django 2.1 on 2021-11-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0025_auto_20211108_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='c2364f2ba06f3e6feb6a8bac5320620884fedd31e04fad30', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='428b3ffa-40a6-11ec-b522-acde48001122', max_length=128, unique=True),
        ),
    ]
