# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_emailconfirmation'),
        ('rps_vendor', '0026_auto_20180826_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCard',
            fields=[
                ('card_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RpsParkingCardSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_id', models.IntegerField()),
                ('debt', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, b'Only created'), (2, b'Inited pay'), (3, b'Authorized pay'), (4, b'Confirmed pay'), (5, b'Error')], default=1)),
                ('client_uuid', models.UUIDField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('parking_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.ParkingCard')),
            ],
        ),
    ]
