# Generated by Django 2.1 on 2021-11-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0026_auto_20211108_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='c2dfdb9856bdfbc55dd07719f739801f68084cb8aa4d7837', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='761e1568-40a6-11ec-bdc5-acde48001122', max_length=128, unique=True),
        ),
    ]
