# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-12 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0027_parkingcard_rpsparkingcardsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsparking',
            name='request_parking_card_debt_url',
            field=models.URLField(default=b'https://parkpass.ru/api/v1/parking/rps/mock/debt/'),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='request_payment_authorize_url',
            field=models.URLField(default=b'https://parkpass.ru/api/v1/parking/rps/mock/authorized/'),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='request_payment_confirm_url',
            field=models.URLField(default=b'https://parkpass.ru/api/v1/parking/rps/mock/confirm/'),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='request_payment_refund_url',
            field=models.URLField(default=b'https://parkpass.ru/api/v1/parking/rps/mock/refund/'),
        ),
    ]
