# Generated by Django 2.1 on 2021-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0027_auto_20211108_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='0c42ea7cdf457817faf9b68e8af77edd86eb8b906dded8c6', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='5c308308-423f-11ec-9e52-acde48001122', max_length=128, unique=True),
        ),
    ]
