# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-23 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0028_auto_20190512_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpsparking',
            name='request_payment_confirm_url',
        ),
        migrations.RemoveField(
            model_name='rpsparking',
            name='request_payment_refund_url',
        ),
    ]
