# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0028_auto_20180718_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 22, 36, 23, 66630)),
        ),
    ]
