# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0030_parkingsession_vendor_id'),
        ('accounts', '0018_auto_20190615_2342'),
        ('rps_vendor', '0029_auto_20190523_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpsSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('sum', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('prolongation', models.BooleanField(default=True)),
                ('data', models.TextField(help_text=b'Byte array as base64')),
                ('idts', models.TextField()),
                ('id_transition', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
            ],
        ),
    ]
