# Generated by Django 2.1 on 2021-11-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0029_auto_20211111_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='4926ec33cff26480000d93ca0c9a82221dbe8d17004a5221', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='c4d595cc-42e1-11ec-91d8-acde48001122', max_length=128, unique=True),
        ),
    ]
