# Generated by Django 2.1 on 2021-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0030_auto_20211111_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='f67321ff6d8896c5af08d0f92d56221aba049854d6582482', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='83b6be48-42e3-11ec-a4df-acde48001122', max_length=128, unique=True),
        ),
    ]
