# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0030_rpssubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpssubscription',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpssubscription',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Only created'), (2, b'Inited pay'), (3, b'Authorized pay'), (4, b'Confirmed pay'), (5, b'Error')], default=1),
        ),
    ]
