# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0031_auto_20190717_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpssubscription',
            name='data',
            field=models.TextField(blank=True, help_text=b'Byte array as base64', null=True),
        ),
    ]
