# Generated by Django 2.2 on 2021-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0031_auto_20211111_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='0bd620c6022d4c499b636f56df1157897bfcedd552c613fc', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='be648572-4b9c-11ec-939e-acde48001122', max_length=128, unique=True),
        ),
    ]
