# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0032_auto_20190717_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsparking',
            name='request_get_subscriptions_list_url',
            field=models.URLField(default=b'https://parkpass.ru/api/v1/parking/rps/mock/subscriptions/'),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='request_subscription_pay_url',
            field=models.URLField(default=b'https://parkpass.ru/api/v1/parking/rps/mock/subscription/pay/'),
        ),
    ]
