# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 13:57
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rps_vendor', '0033_auto_20180718_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 13, 57, 16, 613158)),
        ),
    ]
