# Generated by Django 2.2 on 2022-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0033_auto_20211216_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='03c87827c5c1cf81b3815fd5af3958d581d4f56474905508', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='192b7486-b644-11ec-86d8-acde48001122', max_length=128, unique=True),
        ),
    ]
