# Generated by Django 2.2 on 2022-04-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0034_auto_20220407_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='6094db3886d093feab9d3f136f4f02e5c31a4fffcfe95f4e', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='213de8e6-b650-11ec-8498-acde48001122', max_length=128, unique=True),
        ),
    ]
