# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 09:54
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rps_vendor', '0034_auto_20180719_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 9, 54, 50, 78261)),
        ),
    ]
