# Generated by Django 2.2 on 2022-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0035_auto_20220407_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='eaf69bbf6cc1e3a9a30c4d4c44249cb4442823bf9ce70601', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='7c205faa-b650-11ec-8dbf-acde48001122', max_length=128, unique=True),
        ),
    ]
