# Generated by Django 2.2 on 2022-04-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0036_auto_20220407_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='51c80a8924089f1c8f9330f3b140feb3827b0bb0cfe76988', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='61a6019c-b651-11ec-a0e4-acde48001122', max_length=128, unique=True),
        ),
    ]
