# Generated by Django 2.2 on 2022-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0037_auto_20220407_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='d3b07b058be97a99361dbf4e985e60529170e69b6d577dd8', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='c93fcdc2-b969-11ec-842d-acde48001122', max_length=128, unique=True),
        ),
    ]
