# Generated by Django 2.2 on 2022-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0038_auto_20220411_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='33e74398ae56e4427c23caf080e19c929dee30bc496ad392', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='ebe118a2-bc9a-11ec-a9b9-acde48001122', max_length=128, unique=True),
        ),
    ]
