# Generated by Django 2.2 on 2022-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0039_auto_20220415_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerslog',
            name='message',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='fe7c633c6c69ddd5b137aac3c5a7005aa46c62483f6669e1', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='36b9635c-bfc5-11ec-b90a-acde48001122', max_length=128, unique=True),
        ),
    ]
