# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 11:20
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rps_vendor', '0040_auto_20180722_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpsparking',
            name='last_request_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 11, 20, 39, 160644)),
        ),
    ]
