# Generated by Django 2.2 on 2022-04-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0040_auto_20220419_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='30ce433c4d75f84e39070f144b26b688002f2ef64e568aae', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='aaf90012-c16c-11ec-b6ca-acde48001122', max_length=128, unique=True),
        ),
    ]
