# Generated by Django 2.2 on 2022-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0041_auto_20220421_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='7d2bf36440583aeffb429eb2e82fe320434473c37b2bde19', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='df61d8e2-ca1d-11ec-a780-acde48001122', max_length=128, unique=True),
        ),
    ]
