# Generated by Django 2.2 on 2022-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0042_auto_20220502_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='3d5fef84f17ab027e0a170b173255efb3388a1b8a91c8a2c', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='d2609ee2-cc4f-11ec-ab84-acde48001122', max_length=128, unique=True),
        ),
    ]
