# Generated by Django 2.2 on 2022-05-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0043_auto_20220505_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='94776bb5138d210f59abfe38b80ad0effcc9ff51b9577958', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='0f8868d8-cdf7-11ec-8f1e-acde48001122', max_length=128, unique=True),
        ),
    ]
