# Generated by Django 2.2 on 2022-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0044_auto_20220507_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='e0748272707f6975364879f136352702bcd6db48739250d9', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='5b7c8420-cf8e-11ec-aedc-acde48001122', max_length=128, unique=True),
        ),
    ]
