# Generated by Django 2.2 on 2022-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0045_auto_20220509_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='21a9d153a58e26220caff5a7229bd557f1dcdd34e852869a', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='3909925c-d6af-11ec-9b17-acde48001122', max_length=128, unique=True),
        ),
    ]
