# Generated by Django 2.2 on 2024-07-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0046_auto_20220518_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsparking',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='integrator_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='integrator_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rpsparking',
            name='token_expired',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
