# Generated by Django 2.2 on 2025-02-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0047_auto_20240729_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsparking',
            name='redirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='developer',
            name='api_key',
            field=models.CharField(default='94c73d6c30a7e2061f22da550719b056917500d284802876', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default='e9e075ce-e637-11ef-b453-0242ac12000a', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='developerslog',
            name='message',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='developerslog',
            name='type',
            field=models.IntegerField(choices=[(0, 'Получение задолженности'), (1, 'Оплата задолженности'), (2, 'РПС ответ на получение задолженности'), (4, 'РПС ответ на оплату задолженности')]),
        ),
        migrations.AlterField(
            model_name='rpsparkingcardsession',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'created'), (2, 'inited_pay'), (3, 'authorized_pay'), (4, 'confirmed_pay'), (5, 'error')], default=1),
        ),
    ]
