# Generated by Django 2.2 on 2025-01-01 00:00
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recipient_name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(blank=True, max_length=12)),
                ('bik', models.CharField(max_length=12)),
                ('account', models.CharField(max_length=64)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=16)),
                ('period_days', models.PositiveIntegerField(default=1)),
                ('emails', models.TextField(blank=True)),
                ('auto_send', models.BooleanField(default=False)),
                ('parking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
            ],
            options={'db_table': 'report_settings_parking'},
        ),
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('file_path', models.TextField(blank=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_refund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
            ],
            options={'db_table': 'transaction_report', 'ordering': ['-start']},
        ),
    ]
