# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('accounts', '0001_initial'),
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('comment', models.CharField(blank=True, max_length=1023, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=63, null=True)),
                ('last_name', models.CharField(blank=True, max_length=63, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('sms_code', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(default=b'stub', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('display_id', models.IntegerField()),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_state', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Normal'), (2, 'Test only')], default=1)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('comission', models.FloatField(default=0.02)),
                ('secret', models.CharField(default='stub', max_length=255, unique=True)),
                ('inn', models.CharField(blank=True, max_length=15, null=True)),
                ('kpp', models.CharField(blank=True, max_length=15, null=True)),
                ('bik', models.CharField(blank=True, max_length=15, null=True)),
                ('legal_address', models.CharField(blank=True, max_length=512, null=True)),
                ('actual_address', models.CharField(blank=True, max_length=512, null=True)),
                ('checking_account', models.CharField(blank=True, max_length=64, null=True)),
                ('checking_kpp', models.CharField(blank=True, max_length=15, null=True)),
                ('email_confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EmailConfirmation')),
                ('test_parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_vendor', to='parkings.Parking')),
                ('test_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='VendorSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=63)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
            options={
                'ordering': ['-expired_at'],
                'abstract': False,
            },
        ),
    ]
