# Generated by Django 2.1.5 on 2020-01-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0002_rpssubscription'),
        ('parkings', '0002_auto_20200110_2052'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Session created'), (2, 'Session completed'), (3, 'Session closed'), (4, 'Subscription paid'), (5, 'Parking card session paid')], default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_card_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsParkingCardSession')),
                ('parking_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.ParkingSession')),
                ('rps_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsSubscription')),
            ],
        ),
    ]
