# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='bik',
            new_name='bic',
        ),
    ]
