# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vendors', '0002_auto_20180718_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='secret',
            field=models.CharField(default='stub', max_length=255, unique=True),
        ),
    ]
