# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import owners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20181205_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='inn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(owners.validators.validate_inn,)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='kpp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(owners.validators.validate_kpp,)),
        ),
    ]
