# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vendors', '0003_auto_20180720_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('comment', models.CharField(blank=True, max_length=1023, null=True)),
            ],
        ),
    ]
