# Generated by Django 2.1 on 2021-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20200614_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
    ]
