# Generated by Django 2.1 on 2021-11-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_email_fiskal_notification_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email_fiskal_notification_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
