# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180824_1910'),
        ('parkings', '0017_auto_20180826_1137'),
        ('vendors', '0007_auto_20180722_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_state',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Normal'), (2, 'Test only')], default=1),
        ),
        migrations.AddField(
            model_name='vendor',
            name='comission',
            field=models.FloatField(default=0.02),
        ),
        migrations.AddField(
            model_name='vendor',
            name='display_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='test_parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='parking_vendor', to='parkings.Parking'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='test_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
