# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-09 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20180826_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
