# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-12 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import owners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_auto_20181113_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='bik',
            new_name='bic',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='inn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(owners.validators.validate_inn,)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='kpp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(owners.validators.validate_kpp,)),
        ),
    ]
