# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-10 15:13
from __future__ import unicode_literals

import accounts.validators
import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_auto_20181212_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Type owner'), (2, b'Type vendor')])),
                ('name', models.CharField(max_length=255, validators=(accounts.validators.validate_name,))),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=13, validators=(base.validators.validate_phone_number,))),
                ('comment', models.CharField(blank=True, max_length=1023, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
