# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_vendor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='avatar',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
