# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0030_parkingsession_vendor_id'),
        ('rps_vendor', '0030_rpssubscription'),
        ('vendors', '0016_auto_20190126_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Session created'), (2, 'Session completed'), (3, 'Session closed'), (4, 'Subscription paid'), (5, 'Parking card session paid')], default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_card_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsParkingCardSession')),
                ('parking_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.ParkingSession')),
                ('rps_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsSubscription')),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='fetch_extern_user_data_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
