# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_auto_20190616_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendornotification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='parking_card_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsParkingCardSession'),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='parking_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.ParkingSession'),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='rps_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rps_vendor.RpsSubscription'),
        ),
    ]
