# Generated by Django 2.1.5 on 2020-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('User', 'account'), ('Vendor', 'vendor'), ('Owner', 'owner')], default='account', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_key', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
    ]
