# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='account_type',
            field=models.CharField(choices=[(b'User', b'account'), (b'Vendor', b'vendor'), (b'Owner', b'owner')], default=b'account', max_length=40),
        ),
    ]
