# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_emailconfirmation_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
