# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0003_emailconfirmation_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='account_type',
            field=models.CharField(choices=[(b'User', b'account'), (b'Vendor', b'vendor'), (b'Owner', b'owner')],
                                   default=b'account', max_length=40),
        ),
    ]
