# Generated by Django 2.1 on 2021-08-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
    ]
