# Generated by Django 2.1 on 2021-09-02 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210828_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_picture',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
    ]
