# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notifyissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
