# Generated by Django 2.1 on 2021-09-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210902_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.CharField(default='asdasd', max_length=255),
            preserve_default=False,
        ),
    ]
