# Generated by Django 2.1 on 2021-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
    ]
