# Generated by Django 2.1 on 2021-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=360)),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('sended_at', models.DateField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('all', 'all')], default='all', max_length=10)),
            ],
        ),
    ]
