# Generated by Django 2.1 on 2021-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='sended_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
