# Generated by Django 2.1 on 2021-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20211028_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
