# Generated by Django 2.2 on 2021-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20211028_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='user_ids',
            field=models.TextField(blank=True, help_text='comma separate', null=True),
        ),
    ]
