# Generated by Django 2.2 on 2022-06-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0044_auto_20220616_1139'),
        ('notifications', '0005_mailing_user_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking'),
        ),
    ]
