# Generated by Django 2.2 on 2022-06-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_mailing_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='parkings_sessions_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='parking',
            field=models.ForeignKey(blank=True, help_text='Если выбрана парковка, уведомления будут слаться по юзерам из данного объекта', null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking'),
        ),
    ]
