# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Complain_1'), (2, b'Complain_2'), (3, b'Complain_3'), (4, b'Complain_4'), (5, b'Complain_5')])),
                ('message', models.TextField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=63, null=True)),
                ('city', models.CharField(blank=True, max_length=63, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('enabled', models.BooleanField(default=True)),
                ('parkpass_status', models.IntegerField(choices=[(0, b'Disconnected'), (1, b'Pending'), (2, b'Connected')], default=0)),
                ('free_places', models.IntegerField()),
                ('max_places', models.IntegerField(default=0)),
                ('max_client_debt', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('software_updated_at', models.DateField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False, verbose_name=b'Is approved by administrator')),
                ('tariff', models.CharField(default=b'{}', max_length=2000, verbose_name=b'Tariff object JSON')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parkings',
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session_id', models.CharField(max_length=128)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('state', models.IntegerField(choices=[(-1, b'Canceled'), (1, b'Started_by_client'), (2, b'Started_by_vendor'), (3, b'Started'), (6, b'Completed_by_client'), (7, b'Completed_by_client_fully'), (10, b'Completed_by_vendor'), (11, b'Completed_by_vendor_fully'), (14, b'Completed'), (0, b'Closed'), (21, b'Verification required')])),
                ('started_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('try_refund', models.BooleanField(default=False)),
                ('target_refund_sum', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('current_refund_sum', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Parking Session',
                'verbose_name_plural': 'Parking Sessions',
            },
        ),
        migrations.CreateModel(
            name='UpgradeIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.IntegerField(choices=[(0, b'Software update'), (1, b'Install readers')])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, b'New'), (1, b'Viewed'), (2, b'Processing'), (3, b'Processed'), (-1, b'Cancelled')], default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_by_owner', to='owners.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'verbose_name_plural': 'Wishes',
            },
        ),
    ]
