# Generated by Django 2.1 on 2020-06-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_auto_20200110_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='vendor_id',
            field=models.IntegerField(default=0),
        ),
    ]
