# Generated by Django 2.1 on 2020-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0003_parkingsession_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='rps_subscriptions_available',
            field=models.BooleanField(default=False),
        ),
    ]
