# Generated by Django 2.1 on 2020-09-05 14:58

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0004_parking_rps_subscriptions_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemParkingSessionNotifierSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('report_emails', models.TextField(blank=True, null=True, validators=[base.validators.comma_separated_emails])),
                ('last_email_send_date', models.DateTimeField()),
                ('interval_in_mins', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problem_parking_session_notifier_settings',
            },
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='is_send_warning_non_closed_message',
            field=models.BooleanField(default=False),
        ),
    ]
