# Generated by Django 2.1 on 2024-06-13 03:25

from django.db import migrations, models

def update_parking_session_statuses(apps, schema_editor):
    ParkingSession = apps.get_model('parkings', 'ParkingSession')

    for session in ParkingSession.objects.all():
        if session.state == -1:  # STATE_CANCELED
            continue  # остаётся без изменений
        elif session.state == 0:  # STATE_CLOSED
            continue  # остаётся без изменений
        elif session.state == 3:  # STATE_STARTED
            continue  # остаётся без изменений
        elif session.state == 14:  # STATE_COMPLETED
            continue  # остаётся без изменений
        elif session.state in [6, 7, 10, 11]:  # Completed by client/vendor
            session.state = 23  # STATE_EXIT_ALLOWED
        elif session.state in [1, 2]:  # Started by client/vendor
            session.state = 22  # STATE_ENTER_ALLOWED
        elif session.state == 21:  # Verification required
            session.state = -1  # STATE_CANCELED
            session.error = "Verification required"
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0004_parking_rps_subscriptions_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='state',
            field=models.IntegerField(choices=[(-1, 'Canceled'), (0, 'Closed'), (3, 'Started'), (14, 'Completed'), (22, 'Enter Allowed'), (23, 'Exit Allowed')]),
        ),
        migrations.RunPython(update_parking_session_statuses),
    ]
