# Generated by Django 2.1 on 2021-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0005_auto_20200905_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='manual_pay',
            field=models.BooleanField(default=False),
        ),
    ]