# Generated by Django 2.1 on 2021-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0006_parkingsession_manual_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('KZT', 'KZT'), ('USD', 'USD')], default='RUB', max_length=10),
        ),
    ]
