# Generated by Django 2.1 on 2021-02-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0007_parking_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='bank',
            field=models.CharField(choices=[('tinkoff', 'Tinkoff'), ('homebank', 'Homebank')], default='tinkoff', max_length=20),
        ),
    ]
