# Generated by Django 2.1 on 2021-02-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0008_parking_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='bank',
            new_name='acquiring',
        ),
    ]
