# Generated by Django 2.1 on 2021-03-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0009_auto_20210203_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingsession',
            old_name='manual_pay',
            new_name='manual_close',
        ),
    ]
