# Generated by Django 2.1 on 2021-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0010_auto_20210324_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='canceled_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
