# Generated by Django 2.1 on 2021-11-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0012_parkingsession_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='commission_client',
            field=models.BooleanField(default=False, verbose_name='Комиссию оплачивает клиент'),
        ),
        migrations.AddField(
            model_name='parking',
            name='commission_client_value',
            field=models.IntegerField(default=0, verbose_name='Размер комиссии в процентах'),
        ),
    ]
