# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180509_1130'),
        ('parkings', '0012_auto_20180509_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Complain_1'), (2, b'Complaint_2'), (3, b'Complain_3'), (4, b'Complain_4'), (5, b'Complain_5')])),
                ('message', models.TextField(max_length=1023)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.ParkingSession')),
            ],
        ),
    ]
