# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-07 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0013_complainsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='current_refund_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='target_refund_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='try_refund',
            field=models.BooleanField(default=False),
        ),
    ]
