# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '__first__'),
        ('accounts', '0011_auto_20180824_1910'),
        ('parkings', '0014_auto_20180607_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedParking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='parking',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='wantedparking',
            name='parking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking'),
        ),
        migrations.AddField(
            model_name='wantedparking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
