# Generated by Django 2.1 on 2021-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0014_parking_hide_parking_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='object_images'),
        ),
    ]
