# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_password'),
        ('parkings', '0014_auto_20180607_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedParking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
