# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '__first__'),
        ('parkings', '0014_auto_20180607_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
