# Generated by Django 2.2 on 2022-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0015_parking_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
