# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 13:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0012_account_email_confirmation'),
        ('parkings', '0015_auto_20180718_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedParking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
                ('user',
                 models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
