# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-24 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0015_auto_20180824_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
    ]
