# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('parkings', '0016_wantedparking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WantedParking',
            new_name='Wish',
        ),
    ]
