# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('vendors', '0007_auto_20180722_1326'),
        ('parkings', '0016_auto_20180824_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.IntegerField(choices=[(0, b'Software update'), (1, b'Install readers')])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, b'New'), (1, b'Viewed'), (2, b'Processing'), (3, b'Processed'), (-1, b'Cancelled')], default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_by_owner', to='owners.Owner')),
            ],
        ),
        migrations.RenameModel(
            old_name='WantedParking',
            new_name='Wish',
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name_plural': 'Wishes'},
        ),
        migrations.AddField(
            model_name='parking',
            name='approved',
            field=models.BooleanField(default=False, verbose_name=b'Is approved by administrator'),
        ),
        migrations.AddField(
            model_name='parking',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Owner'),
        ),
        migrations.AlterField(
            model_name='complainsession',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Complain_1'), (2, b'Complain_2'), (3, b'Complain_3'), (4, b'Complain_4'), (5, b'Complain_5')]),
        ),
        migrations.AddField(
            model_name='upgradeissue',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_by_vendor', to='vendors.Vendor'),
        ),
    ]
