# Generated by Django 2.2 on 2022-04-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0017_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='comment',
            new_name='desc',
        ),
    ]
