# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parkings', '0017_auto_20180720_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='approved',
            field=models.BooleanField(default=False, verbose_name=b'Is approved by administrator'),
        ),
    ]
