# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-26 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0017_auto_20180826_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]