# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-09 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_company_connectissue_issue'),
        ('parkings', '0018_delete_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='owner',
        ),
        migrations.AddField(
            model_name='parking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Company'),
        ),
        migrations.AddField(
            model_name='parking',
            name='max_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='parkpass_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parking',
            name='software_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
