# Generated by Django 2.2 on 2022-04-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0018_auto_20220407_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='parkings.Service'),
        ),
    ]
