# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('parkings', '0018_parking_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name_plural': 'Wishes'},
        ),
    ]
