# Generated by Django 2.2 on 2022-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0019_parking_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='card_commission_client_value',
            field=models.IntegerField(default=0, verbose_name='Размер комиссии в процентах (карты)'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='services',
            field=models.ManyToManyField(blank=True, to='parkings.Service'),
        ),
    ]
