# Generated by Django 2.2 on 2022-05-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0042_auto_20220502_1343'),
        ('owners', '0022_auto_20220430_0959'),
        ('parkings', '0020_auto_20220411_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingValetSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=50, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Принял автомобиль'), (2, 'Парковка автомобиля'), (3, 'Автомобиль припаркован'), (4, 'Запрошена подача автомобиля'), (5, 'В процессе подачи'), (6, 'Машина выдана'), (7, 'Валет сессия завершена'), (8, 'Сессия завершена и оплачена')], default=1)),
                ('car_number', models.CharField(max_length=20)),
                ('car_color', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='valet_car_photo')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valet_card_id', models.CharField(max_length=100)),
                ('parking_floor', models.SmallIntegerField(default=1)),
                ('parking_space_number', models.CharField(max_length=20)),
                ('parking_card_get_at', models.DateTimeField(blank=True, null=True)),
                ('car_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('car_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('manual_close', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('started_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('car_delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_delivered_by_relate_table', to='owners.CompanyUser')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user_relate_table', to='owners.CompanyUser')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
                ('parking_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rps_vendor.ParkingCard')),
                ('parking_card_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rps_vendor.RpsParkingCardSession')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_relate_table', to='owners.CompanyUser')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingValetSessionRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ожидает принятия'), (1, 'Запрос принят'), (1, 'Запрос отменен')], default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('car_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('valet_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.ParkingValetSession')),
            ],
        ),
    ]
