# Generated by Django 2.2 on 2022-04-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0021_parkingvaletsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingValetSessionRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ожидает принятия'), (1, 'Запрос принят'), (1, 'Запрос отменен')], default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('car_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('valet_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.ParkingValetSession')),
            ],
        ),
    ]
