# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0021_auto_20181017_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
