# Generated by Django 2.2 on 2022-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0021_parkingvaletsession_parkingvaletsessionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingvaletsession',
            name='parking_card_get_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parkingvaletsessionrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ожидает принятия'), (2, 'Запрос принят'), (3, 'Запрос отменен')], default=1),
        ),
    ]
