# Generated by Django 2.2 on 2022-05-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0022_auto_20220430_0959'),
        ('parkings', '0022_auto_20220504_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingvaletsession',
            old_name='responsible',
            new_name='responsible_for_reception',
        ),
        migrations.AddField(
            model_name='parkingvaletsession',
            name='responsible_for_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_delivery_relate_table', to='owners.CompanyUser'),
        ),
        migrations.AddField(
            model_name='parkingvaletsessionrequest',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.CompanyUser'),
        ),
        migrations.AlterField(
            model_name='parkingvaletsession',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Принял автомобиль'), (2, 'Парковка автомобиля'), (3, 'Автомобиль припаркован'), (4, 'Запрошена подача автомобиля'), (5, 'В процессе подачи'), (6, 'Машина ожидает'), (7, 'Машина выдана'), (8, 'Валет сессия завершена'), (9, 'Сессия завершена и оплачена')], default=1),
        ),
    ]
