# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-12 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0022_parkingsession_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='parkpass_enabled',
        ),
        migrations.AddField(
            model_name='parking',
            name='city',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='parkpass_status',
            field=models.IntegerField(choices=[(0, b'Disconnected'), (1, b'Pending'), (2, b'Connected')], default=0),
        ),
    ]
