# Generated by Django 2.2 on 2022-05-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0022_auto_20220430_0959'),
        ('parkings', '0023_auto_20220505_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingvaletsession',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Company'),
        ),
        migrations.AlterField(
            model_name='parkingvaletsession',
            name='responsible_for_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_delivery_relate_table', to='owners.CompanyUser'),
        ),
    ]
