# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0009_auto_20190110_1513'),
        ('parkings', '0023_auto_20181212_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradeissue',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='upgradeissue',
            name='vendor',
        ),
        migrations.AddField(
            model_name='parking',
            name='max_permitted_time',
            field=models.IntegerField(default=3600, help_text=b'Max offline time in minutes'),
        ),
        migrations.AddField(
            model_name='parking',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Owner'),
        ),
        migrations.DeleteModel(
            name='UpgradeIssue',
        ),
    ]
