# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0024_auto_20190110_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='tariff_file_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='tariff_file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
