# Generated by Django 2.2 on 2022-05-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0022_auto_20220430_0959'),
        ('parkings', '0024_auto_20220506_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingvaletsessionrequest',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owners.Company'),
        ),
    ]
