# Generated by Django 2.2 on 2022-05-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0026_auto_20220506_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingvaletsession',
            name='car_photo',
        ),
        migrations.CreateModel(
            name='ParkingValetSessionImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Фото при приеме'), (2, 'Фото с парковки')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='valet_car_photo')),
                ('valet_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.ParkingValetSession')),
            ],
        ),
    ]
