# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_emailconfirmation'),
        ('parkings', '0026_auto_20190323_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopParkingWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('parking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
                ('users', models.ManyToManyField(to='accounts.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='parkingsession',
            name='state',
            field=models.IntegerField(choices=[(-1, b'Canceled'), (1, b'Started_by_client'), (2, b'Started_by_vendor'), (3, b'Started'), (6, b'Completed_by_client'), (7, b'Completed_by_client_fully'), (10, b'Completed_by_vendor'), (11, b'Completed_by_vendor_fully'), (14, b'Completed without client start'), (15, b'Completed'), (0, b'Closed'), (21, b'Verification required')]),
        ),
    ]
