# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0027_auto_20190423_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking'),
        ),
    ]
