# Generated by Django 2.2 on 2022-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0027_auto_20220507_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingvaletsession',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
