# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0028_auto_20190518_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='rps_parking_card_available',
            field=models.BooleanField(default=False),
        )
    ]