# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0029_auto_20190523_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='vendor_id',
            field=models.IntegerField(default=0),
        ),
    ]
