# Generated by Django 2.2 on 2022-05-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps_vendor', '0045_auto_20220509_1151'),
        ('parkings', '0029_remove_parkingvaletsession_parking_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingvaletsession',
            name='parking_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rps_vendor.ParkingCard'),
        ),
    ]
