# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0030_parkingsession_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='rps_subscriptions_available',
            field=models.BooleanField(default=False),
        ),
    ]
