# Generated by Django 2.2 on 2022-05-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0032_auto_20220513_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingvaletsessionrequest',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingvaletsession',
            name='car_color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
