# Generated by Django 2.2 on 2022-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0033_auto_20220513_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingvaletsessionimages',
            name='img',
            field=models.CharField(max_length=128),
        ),
    ]
