# Generated by Django 2.2 on 2022-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0035_auto_20220524_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingvaletsession',
            name='parking_card',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
