# Generated by Django 2.2 on 2022-06-13 05:59

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    from parkings.models import Parking
    for device in Parking.objects.all():
        device.valet_telegram_secret_key = uuid.uuid4()
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0037_parking_valet_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='valet_telegram_secret_key',
            field=models.CharField(editable=False, blank=True, null=True, max_length=128),
        ),
        migrations.RunPython(create_uuid),
    ]
