# Generated by Django 2.2 on 2022-06-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0039_auto_20220613_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingValetTelegramChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.Parking')),
            ],
        ),
    ]
