# Generated by Django 2.2 on 2022-06-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0040_parkingvalettelegramchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingvalettelegramchat',
            name='valet_telegram_secret_key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
