# Generated by Django 2.2 on 2022-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0041_parkingvalettelegramchat_valet_telegram_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingvaletsessionrequest',
            name='notificated_about_car_book',
            field=models.BooleanField(default=False),
        ),
    ]
