# Generated by Django 2.2 on 2022-12-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0044_auto_20220616_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
