# Generated by Django 2.2 on 2024-11-10 06:54

from django.db import migrations


def update_started_by_vendor_to_enter_allowed(apps, schema_editor):
    ParkingSession = apps.get_model("parkings", "ParkingSession")
    ParkingSession.objects.filter(state=2).update(
        state=1
    )  # 2 соответствует STATE_STARTED_BY_VENDOR, 1 соответствует ENTER_ALLOWED


class Migration(migrations.Migration):

    dependencies = [
        ("parkings", "0045_parking_domain"),
    ]

    operations = [
        migrations.RunPython(update_started_by_vendor_to_enter_allowed),
    ]
