# Generated by Django 2.2 on 2024-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0046_auto_20241110_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='state',
            field=models.IntegerField(choices=[(-1, 'Canceled'), (1, 'Enter_allowed'), (3, 'Started'), (6, 'Completed_by_client'), (7, 'Completed_by_client_fully'), (10, 'Completed_by_vendor'), (11, 'Completed_by_vendor_fully'), (14, 'Completed without client start'), (15, 'Completed'), (0, 'Closed'), (21, 'Verification required')]),
        ),
    ]
