# Generated by Django 2.2 on 2024-11-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0049_auto_20241110_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='error',
            field=models.CharField(default='', max_length=255),
        ),
    ]
