# Generated by Django 2.2 on 2024-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0051_auto_20241110_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='state',
            field=models.IntegerField(choices=[(-1, 'Canceled'), (1, 'Enter_allowed'), (3, 'Started'), (12, 'Exit_allowed'), (14, 'Completed without client start'), (15, 'Completed'), (0, 'Closed')]),
        ),
    ]
