# Generated by Django 2.2 on 2024-11-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0052_auto_20241110_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingsession',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='parkingsession',
            name='suspended_at',
        ),
    ]
