# Generated by Django 2.2 on 2024-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0053_auto_20241110_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='device_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='e_ticket',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='qr_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
